import { Router } from "express";
import { AuthMiddleware } from "../middleware/authMiddleware.js";
import { UserController } from "../controller/userController.js";
const router = Router();
const userController = new UserController();
router.post("/create", AuthMiddleware, userController.CreateUser);
router.put("/update", AuthMiddleware, userController.UpdateUser);
router.get("/find-all", AuthMiddleware, userController.FindAll);
router.delete("/delete", AuthMiddleware, userController.DeleteUser);
router.get("/getprofile", AuthMiddleware, userController.GetProfile);
router.post("/check-contacts", AuthMiddleware, userController.checkContact);
export default router;
